### ISSUE TITLE
Speedup `sample` method

### ISSUE THREAD

**Issue by manujosephv** [sagelywizard/pytorch-mdn#8]
The sample method can be sped up ~10x by using torch.gather

``` python
def sample(self, pi, sigma, mu):
        """Draw samples from a MoG."""
        categorical = Categorical(pi)
        pis = categorical.sample().unsqueeze(1)
        sample = Variable(sigma.data.new(sigma.size(0), 1).normal_())
        # Gathering from the two Gaussian Distribution based on sampled indices
        sample = sample * sigma.gather(1, pis) + mu.gather(1, pis)
        return sample
````

**Comment by sagelywizard** [comment]
Thanks, I made your suggestion! I did a quick profile and it looks like a 30x speedup on my laptop.

**Comment by manujosephv** [comment]
Have taken inspiration from your code and have reimplemented in my library for tabular data https://github.com/manujosephv/pytorch_tabular/blob/main/pytorch_tabular/models/mixture_density/mdn.py

Have added a lot more tweaks to make the MDN training more stable.
